/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.inject.Guice;
import com.google.inject.Inject;
import com.google.inject.Injector;
import dev.langchain4j.model.chat.ChatLanguageModel;
import io.github.cdimascio.dotenv.Dotenv;

import java.util.Arrays;
import java.util.List;

public class App {
    private static final String OPENAI_MODEL = "openai";
    private static final String ANTHROPIC_MODEL = "anthropic";
    private static final String DEFAULT_MODEL = OPENAI_MODEL;

    public static void main(String[] args) {
        Dotenv dotenv = Dotenv.load();

        List<String> argsList = Arrays.asList(args);
        int modelNameIndex = argsList.indexOf("--model");
        String modelNameValue = (modelNameIndex >= 0) ? argsList.get(modelNameIndex + 1) : DEFAULT_MODEL;

        com.google.inject.Module aiModule = switch (modelNameValue) {
            case OPENAI_MODEL -> new OpenAiModule(dotenv);
            case ANTHROPIC_MODEL -> new AnthropicModule(dotenv);
            default -> throw new IllegalStateException("Unexpected value: " + modelNameValue);
        };

        Injector injector = Guice.createInjector(aiModule);
        App app = injector.getInstance(App.class);
        System.out.println(app.getGreeting());
    }

    private final ChatLanguageModel chatLanguageModel;

    @Inject
    public App(ChatLanguageModel chatLanguageModel) {
        this.chatLanguageModel = chatLanguageModel;
    }

    public String getGreeting() {
//        return "Hello World!";
        return chatLanguageModel.generate("Hello world!");
    }
}
