/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.inject.Inject;
import dev.langchain4j.model.chat.ChatLanguageModel;

public class App {
    private final ChatLanguageModel chatLanguageModel;

    @Inject
    public App(ChatLanguageModel chatLanguageModel) {
        this.chatLanguageModel = chatLanguageModel;
    }

    public String getGreeting() {
//        return "Hello World!";
        return chatLanguageModel.generate("Hello world!");
    }
}
