/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private final App sut = new App();

    @Test
    void appHasAGreeting() {
        // Given

        // When
        var actualGreeting = sut.getGreeting();

        // Then
        assertNotNull(actualGreeting, "app should have a greeting");
    }
}
